### ISSUE TITLE
Geographic Coverage CSV not pulling much data

### ISSUE THREAD

**Issue by AnissaPierre** [mitmedialab/MediaCloud-Web-Tools#1363]
When you download the CSV from the map in Explorer you get very limited results. Maybe there's some kind of threshold on the data?
<img width="1329" alt="screen shot 2018-11-13 at 9 33 40 am" src="https://user-images.githubusercontent.com/25494330/48419955-3c86ad00-e727-11e8-8a42-87f724cdef2a.png">

**Comment by AnissaPierre** [comment]
The query I used is all stories, U.S. Top Online News 2017 (default collection,) from 10/13/2018 to 11/13/2018

https://explorer.mediacloud.org/#/queries/search?q=[{%22label%22:%22(all%20stories)%22,%22q%22:%22%22,%22color%22:%22%231f77b4%22,%22startDate%22:%222018-10-13%22,%22endDate%22:%222018-11-13%22,%22sources%22:[],%22collections%22:[58722749]}]&auto=true

**Comment by cindyloo** [comment]
this is happening in the `_filter_for_countries` python call in `explorer/geo.py`
```def _filter_for_countries(top_geo_tags):
    # this tag set has country and state tags, so we have to filter out to get just the country ones to draw a heatmap
    # 1: parse out the geonames id from the tag (ie. "geonames_6252001" and verify it on the whitelist
    country_tags = [t for t in top_geo_tags if int(t['tag'].split('_')[1]) in COUNTRY_GEONAMES_ID_TO_APLHA3.keys()]
```

so most of the top_geo_tags passed into this method are parsed out. @rahulbot what do you suggest - show them anyway?

**Comment by cindyloo** [comment]
updated the tag limit to 50 to encompass more of the white-listed values. This was the simplest fix.
