### ISSUE TITLE
manually editing topics urls is wonky

### ISSUE THREAD

**Issue by hroberts** [mitmedialab/MediaCloud-Web-Tools#1440]
I get wonky results whenever I try to manually edit a topic url and reload it by pressing 'enter' in the url bar.  For example, if I load one topic and then try to make another load by manually editing the topics_id in the url and hitting enter, I just get the contents of the original url.  

This is obviously a geeky way to interface with the app, but I've had to explain to a couple of other researchers that this does not work.  I have gotten into the habit of just creating a new tab, copying the edited url into the url bar of the new tab, and going from there.  That works fine for me, but this seems to be tripping up other (albeit geeky) folks.

**Comment by dsjen** [comment]
I'm going to say this is a use case that we don't support :)
