### ISSUE TITLE
First Sample Search On The Homepage of Explorer Is Broken

### ISSUE THREAD

**Issue by sandsfish** [mitmedialab/MediaCloud-Web-Tools#1527]
The first sample search on the homepage of Explorer is broken.

![Screen Shot 2019-04-12 at 1 49 07 PM](https://user-images.githubusercontent.com/302313/56056333-d8920000-5d29-11e9-82e6-039094ea33e9.png)

Clicking on the thumbnail results in "Oops! Something went wrong [object Object]"

![Screen Shot 2019-04-12 at 1 48 48 PM](https://user-images.githubusercontent.com/302313/56056339-de87e100-5d29-11e9-898f-7b472c60ff43.png)

URL:
https://explorer.mediacloud.org/#/queries/demo/0

**Comment by sandsfish** [comment]
The other two thumbnail links are broken as well, same error. 

This is on macOS Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by cindyloo** [comment]
fixed
