### ISSUE TITLE
Change language of attention over time download options

### ISSUE THREAD

**Issue by AnissaPierre** [mitmedialab/MediaCloud-Web-Tools#1589]
It should say "counts" instead of "stories"
<img width="1280" alt="Screen Shot 2019-06-04 at 9 45 27 AM" src="https://user-images.githubusercontent.com/25494330/58883990-81673680-86ad-11e9-9833-c80569475861.png">

**Comment by cindyloo** [comment]
we aren't downloading stories here but count, total count, ratio info. Maybe replace 'stories' with 'statistics' or something like that?
