### ISSUE TITLE
Story download fails when "All Media" is selected (Explorer)

### ISSUE THREAD

**Issue by ebndulue** [mitmedialab/MediaCloud-Web-Tools#1735]
When a user chose All Media as their media option in Explorer, the story download fails. This is even when the number of stories is small. I have confirmed this error in tests myself.

**Comment by cindyloo** [comment]
we've encoded the "All Media" non-collection collection to -1. We weren't handling that in our collection processing in Python.

**Comment by cindyloo** [comment]
related to #1733
