### ISSUE TITLE
inconsistency in notification of Topic "ready" status and still generating

### ISSUE THREAD

**Issue by cindyloo** [mitmedialab/MediaCloud-Web-Tools#1816]
I received an email that my topic was "ready," however, I went to the topic and it said "still generating"
<img width="1062" alt="Screen Shot 2020-05-04 at 12 18 31 PM" src="https://user-images.githubusercontent.com/659092/80988440-8672bf80-8e01-11ea-815d-6631334c54e7.png">
<img width="707" alt="Screen Shot 2020-05-04 at 12 18 25 PM" src="https://user-images.githubusercontent.com/659092/80988444-883c8300-8e01-11ea-8c02-7cf51ee63c24.png">

**Comment by cindyloo** [comment]
now the Topic summary screen shows. Not sure if it is a page caching issue or what...

**Comment by hroberts** [comment]
this is a known bug.  we send the email out when the snapshotting process
is done, but at that point there may still be stories in the solr import
queue.  the snapshot.is_searchable field is not set until there are no more
stories for the given snapshot in the solr import queue.  for small topics,
this usually happens within a few minutes.  for big topics, it can take
several hours.

this is a backend issue.

-hal

**Comment by dsjen** [comment]
Addressed on the backend
