### ISSUE TITLE
Additional queries don't appear in Explorer in attention over time & total attention widgets

### ISSUE THREAD

**Issue by ebndulue** [mitmedialab/MediaCloud-Web-Tools#1915]
When I add a query to my original, I am not seeing data for the secondary query populate in the Attention Over Time widget or the Total Attention widget.

**Comment by dsjen** [comment]
I can confirm that I do not see anything either:

![Screen Shot 2020-06-18 at 12 49 48 PM](https://user-images.githubusercontent.com/5265058/85049282-779e5d00-b162-11ea-9129-6cd7ad08a628.png)

When I refresh the page with the same query args, I do see the trend line appear.

Currently viewing `v3.14.1`

**Comment by dsjen** [comment]
Looking at the states, the format of the UUID seems to change when the query is first loaded vs. a page reload. I think that perhaps an ID is referenced when a UUID should be resulting in the lack of trend line.

![Screen Shot 2020-06-19 at 9 13 02 AM](https://user-images.githubusercontent.com/5265058/85136247-58a8d500-b20d-11ea-9644-84a6a82c139e.png)

**Comment by dsjen** [comment]
@cindyloo / @rahulbot -- I've tracked this down to https://github.com/mitmedialab/MediaCloud-Web-Tools/blob/70d8c56b8f61e0f300a7175259ef2f21d11f93dc/src/lib/explorerUtil.js#L82. If cast into a string, the ID is able to be found (b/c the key is returned as a string, whereas the uid is an int). I can make a PR to fix this, but I think another solution may be to track down why the ID is an int rather.

Is that worth investigating?
