### ISSUE TITLE
MediaPicker may not show Pub State results correctly

### ISSUE THREAD

**Issue by cindyloo** [mitmedialab/MediaCloud-Web-Tools#1935]
queries on Pub State like "massachussets" or "georgia" result in 0 results.

also, below is a a typo that sometimes shows up

<img width="707" alt="Screen Shot 2020-07-10 at 7 58 48 PM" src="https://user-images.githubusercontent.com/659092/87211751-00836100-c2e9-11ea-9223-3d36fab8b092.png">

**Comment by dsjen** [comment]
Thanks! Just to clarify, is the "typo" is the "null" in the screenshot?

**Comment by cindyloo** [comment]
technically, it's not really a typo - it is likely that the `lookupByTagId` hasn't returned the label name yet.

**Comment by dsjen** [comment]
It looks like for the ones that are failing, perhaps the collections themselves have changed:
* Massachusetts points to https://sources.mediacloud.org/#/collections/9360578, which has no sources. Should this be  updated to updated to the state and local version instead, https://sources.mediacloud.org/#/collections/38381372 ?
* California points to https://sources.mediacloud.org/#/collections/9360558, which has no sources
* Georgia points to https://sources.mediacloud.org/#/collections/9360565, which has no sources

@cindyloo / @rahulbot -- should all these be updated to the State and Local collections instead?
