### ISSUE TITLE
Admin analytics table errors on "Collection based on Explorer Queries"

### ISSUE THREAD

**Issue by dsjen** [mitmedialab/MediaCloud-Web-Tools#1936]
The server was throwing a 500 and it turns out that there was a record in mongo with an `id` of `-1`. This was causing an index error in https://github.com/mitmedialab/MediaCloud-Web-Tools/blob/main/server/views/admin/analytics.py#L30.

I spot fix this by deleting the document: `db.analytics.find({id: -1})`. The analytics page loads again fine afterwards.

However, this doesn't address the problem of bad ids. Explorer uses `-1` as a placeholder for “all media”, and this is likely what is being used and tracked. In `AnalyticsDatabase.increment_count` we should ignore values of `-1`.

**Comment by cindyloo** [comment]
this looks to be fixed already? 
`if (the_id is not None) and (len(the_id) > 0):` in `database.py`

**Comment by dsjen** [comment]
I believe the problem is if `the_id` is a string, e.g. `"-1"` this still passes and results in the problem.

**Comment by cindyloo** [comment]
ah ok then i'll convert it to an int within that test

**Comment by cindyloo** [comment]
oh right of course. we pass the string "-1" and I misread that test too
