### ISSUE TITLE
refactor various SCSS properties for MediaPicker/search

### ISSUE THREAD

**Issue by cindyloo** [mitmedialab/MediaCloud-Web-Tools#1944]
for example
 src/styles/sources/_search.scss 
 30px is used a few times. Can this be pulled out into a variable?

`     .select-media-ok-button {
        margin-left: 30px;
      }
`
`.select-media-menu {
        .select-media-option {
`
`.select-media-sidebar-sources` appears to be the same value as used in `select-media-content-sources`'s margin-left. Can that value be moved into a variable?
          padding: 30px;

and src/styles/app/mediapicker/_advanced_source_search.scss

**Comment by dsjen** [comment]
Is this done?
