### ISSUE TITLE
Sources missing from search

### ISSUE THREAD

**Issue by dsjen** [mitmedialab/MediaCloud-Web-Tools#1955]
@titinfoundation reports that some sources cannot be found in search:

- http://www.pakistanlink.org/
- http://www.zehabesha.com/
- https://www.discovery.com/ 
- http://www.fark.com 
- http://www.livescience.com 
- http://www.observer.com 

@titinfoundation, I'm not seeing this problem in the media picker or the search bar. Can you let me know if this is still a problem or if I'm missing something?

**search bar**
<img width="585" alt="Screen Shot 2020-07-30 at 2 12 27 PM" src="https://user-images.githubusercontent.com/5265058/88958659-cca7b580-d26e-11ea-8ce2-4f502e41c4b2.png">

**media picker**
<img width="937" alt="Screen Shot 2020-07-30 at 2 10 34 PM" src="https://user-images.githubusercontent.com/5265058/88958663-cca7b580-d26e-11ea-9f2a-2e7810ad4a56.png">

**Comment by titinfoundation** [comment]
@dsjen apparently the computer wanted to fool me lol, I found the all this time! never mind then. sorry!

**Comment by dsjen** [comment]
No worries!
