### ISSUE TITLE
Unable to change source name because multiple URLs attached to source

### ISSUE THREAD

**Issue by dsjen** [mitmedialab/MediaCloud-Web-Tools#1956]
@titinfoundation reports that it's not possible to change source names for the following because multiple URLs are attached:

- http://watchdog.org#spider 
- http://nationalenquirer.com/ 
- http://www.bizjournals.com 
- http://www.lexisnexis.com/news/ 

@titinfoundation -- I'm not familiar with this issue. Can you describe the steps that you're taking and where it goes wrong, as well as what your expectations are? Thanks!

**Comment by titinfoundation** [comment]
@dsjen I guess now that I look at it in more detail and know more about the platform I can say that what seems to be happening is this: 
<img width="923" alt="Screen Shot 2020-08-07 at 2 15 34 PM" src="https://user-images.githubusercontent.com/64150394/89675774-811d8900-d8b8-11ea-96e4-73e81c50725d.png">

We have a case like bizjournals where there are other sources that were created from them for other states, so if you alter the original you alter those. Nevertheless, they do seem separate now so maybe this is a non issues.
