### ISSUE TITLE
Page won't allow source metadata or feed modification 

### ISSUE THREAD

**Issue by titinfoundation** [mitmedialab/MediaCloud-Web-Tools#1971]
@dsjen and @cindyloo Whenever I go to individual sources and try to modify their metadata or feeds I get hit with this -->

this appear whenever I try to change metadata from source on any collection: 
<img width="781" alt="Screen Shot 2020-08-17 at 6 11 24 PM" src="https://user-images.githubusercontent.com/64150394/90450451-c2cbe200-e0b7-11ea-823b-451e28209fcf.png">
<img width="805" alt="Screen Shot 2020-08-17 at 6 09 21 PM" src="https://user-images.githubusercontent.com/64150394/90450453-c495a580-e0b7-11ea-969e-5056a53c141e.png">

This bellow appears whenever I try to modify the feed of any source on any location: 
<img width="1142" alt="Screen Shot 2020-08-17 at 6 29 53 PM" src="https://user-images.githubusercontent.com/64150394/90450463-c8292c80-e0b7-11ea-8608-778613cf3bc6.png">

**Comment by dsjen** [comment]
Thanks for reporting this! Seems like a pretty essential feature. I'm going to throw it in the high priority queue (let me now if it's not though as things in this queue bump other work).

**Comment by titinfoundation** [comment]
It high priority thanks Denis!
