### ISSUE TITLE
Search Explorer 404 Message

### ISSUE THREAD

**Issue by titinfoundation** [mitmedialab/MediaCloud-Web-Tools#1981]
Whenever you click on the search explorer link of the media sources it sends you to a 404 message. Even if the source exits.
Examples: 

- https://sources.mediacloud.org/#/sources/661465

- https://sources.mediacloud.org/#/sources/194718

- https://sources.mediacloud.org/#/sources/661572

**Comment by dsjen** [comment]
This is very strange, but I do not see this behavior when clicking on the search in explorer link. Can you please try again and let me know if it's still happening?

**Comment by titinfoundation** [comment]
Those seem to be working now lol. In an attempt to make me look bad but look at this one:

- https://sources.mediacloud.org/#/sources/105818/feeds

**Comment by dsjen** [comment]
Ok, thanks for rechecking that! Because we're operating at very diminished computing power right now, I imagine something went awry earlier resulting in the 4040s.

**Comment by titinfoundation** [comment]
@dsjen  I do have other links that are doing it now if you want me to add them all here

**Comment by dsjen** [comment]
Please do!!!
