### ISSUE TITLE
Source Feed works shows in explorer but source manager says it needs review and has no stories (Sources in PodCast Collection)

### ISSUE THREAD

**Issue by titinfoundation** [mitmedialab/MediaCloud-Web-Tools#1991]
https://sources.mediacloud.org/#/sources/1363108 
https://sources.mediacloud.org/#/sources/1363082 
https://sources.mediacloud.org/#/sources/1363086 (scrape is not updated)
https://sources.mediacloud.org/#/sources/1363107 
 https://sources.mediacloud.org/#/sources/1363091 (scrape is not updated)
https://sources.mediacloud.org/#/sources/1363098 (scrape is not updated)

**Comment by dsjen** [comment]
Very interesting! I can confirm that it explorer suggests that there are recent stories, but source manager says that there aren't.

**Comment by dsjen** [comment]
Note for self: I believe there's some oddity with how the stories in the last 90 days are calculated and I suspect that the fix that I did for #1989 may solve this issue and #1953 (another issue with review status).

**Comment by dsjen** [comment]
This will be fixed by https://github.com/mediacloud/backend/issues/726
