### ISSUE TITLE
media source csv upload failed to create tag

### ISSUE THREAD

**Issue by hroberts** [mitmedialab/MediaCloud-Web-Tools#521]
I uploaded the attached csv of media sources, then clicked the button to create the collection.  I got an email with the mostly successful results of the media additions shortly after, but I got the following screen, and the tag was not added at all to the system.

**Comment by hroberts** [comment]
![media_bug](https://user-images.githubusercontent.com/1830735/28083544-4ef39034-663b-11e7-83c9-621de827a11e.png)


[china_sources.txt](https://github.com/mitmedialab/MediaCloud-Web-Tools/files/1139852/china_sources.txt)

**Comment by cindyloo** [comment]
will debug but from the screenshot and corresponding csv, we should be grabbing the auto-gen'd name for sources that are uploaded without a name (default to supplied url).

**Comment by cindyloo** [comment]
ok, looks like we've got an error b/c we aren't returning the media_ids after the creation...
`message
:
"Error - got a HTTP status code of 500 with the message "Internal Server Error", body: {"error":"Error(s): Caught exception in MediaWords::Controller::Api::V2::Media->put_tags \"each record must include a 'media_id' field at lib/MediaWords/Controller/Api/V2/MC_REST_SimpleObject.pm line 623, <$fh> line 1.\n\tMediaWords::Controller::Api::V2::MC_REST_SimpleObject::_process_single_put_tag(MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220), HASH(0xeb77f80)) called at lib/MediaWords/Controller/Api/V2/MC_REST_SimpleObject.pm line 678\n\tMediaWords::Controller::Api::V2::MC_REST_SimpleObject::process_put_tags(MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at lib/MediaWords/Controller/Api/V2/Media.pm line 468\n\tMediaWords::Controller::Api::V2::Media::put_tags_PUT(MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Action.pm line 352\n\tCatalyst::Action::execute(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at lib/MediaWords/ActionRole/RoleAuthenticated.pm line 42\n\tClass::MOP::Class:::around(CODE(0x58a6990), Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 164\n\tClass::MOP::Method::Wrapped::__ANON__(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at lib/MediaWords/ActionRole/Throttled.pm line 118\n\tClass::MOP::Class:::around(CODE(0xbc83f20), Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 164\n\tClass::MOP::Method::Wrapped::__ANON__(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at lib/MediaWords/ActionRole/Logged.pm line 28\n\tClass::MOP::Class:::around(CODE(0xbc79760), Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 164\n\tMoose::Meta::Class::__ANON__::SERIAL::29::_wrapped_execute(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 95\n\tMoose::Meta::Class::__ANON__::SERIAL::29::execute(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2027\n\teval {...} called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2027\n\tCatalyst::execute(MediaWords=HASH(0xc4fe220), \"MediaWords::Controller::Api::V2::Media\", Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Plugin/Authorization/ACL.pm line 39\n\tCatalyst::Plugin::Authorization::ACL::execute(MediaWords=HASH(0xc4fe220), \"MediaWords::Controller::Api::V2::Media\", Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Plugin/StackTrace.pm line 23\n\tCatalyst::Plugin::StackTrace::execute(MediaWords=HASH(0xc4fe220), \"MediaWords::Controller::Api::V2::Media\", Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Action/REST.pm line 149\n\tCatalyst::Action::REST::_dispatch_rest_method(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords=HASH(0xc4fe220), \"put_tags_PUT\") called at lib/Catalyst/Action/MC_REST.pm line 44\n\tCatalyst::Action::MC_REST::dispatch(Moose::Meta::Class::__ANON__::SERIAL::29=HASH(0xbd560d8), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Controller.pm line 171\n\tCatalyst::Controller::_ACTION(MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Action.pm line 352\n\tCatalyst::Action::execute(Catalyst::Action=HASH(0xbd4e9d0), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2027\n\teval {...} called at /home/mediacloud/mediacloud…ler::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Action.pm line 352\n\tCatalyst::Action::execute(Catalyst::Action=HASH(0xbd4d038), MediaWords::Controller::Api::V2::Media=HASH(0xb963700), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2027\n\teval {...} called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2027\n\tCatalyst::execute(MediaWords=HASH(0xc4fe220), \"MediaWords::Controller::Api::V2::Media\", Catalyst::Action=HASH(0xbd4d038)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Plugin/Authorization/ACL.pm line 39\n\tCatalyst::Plugin::Authorization::ACL::execute(MediaWords=HASH(0xc4fe220), \"MediaWords::Controller::Api::V2::Media\", Catalyst::Action=HASH(0xbd4d038)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Plugin/StackTrace.pm line 23\n\tCatalyst::Plugin::StackTrace::execute(MediaWords=HASH(0xc4fe220), \"MediaWords::Controller::Api::V2::Media\", Catalyst::Action=HASH(0xbd4d038)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Action.pm line 347\n\tCatalyst::Action::dispatch(Catalyst::Action=HASH(0xbd4d038), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Dispatcher.pm line 262\n\tCatalyst::Dispatcher::_do_forward(Catalyst::Dispatcher=HASH(0x4fc8950), \"forward\", MediaWords=HASH(0xc4fe220), \"/api/v2/media/_DISPATCH\") called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Dispatcher.pm line 242\n\tCatalyst::Dispatcher::forward(Catalyst::Dispatcher=HASH(0x4fc8950), MediaWords=HASH(0xc4fe220), \"/api/v2/media/_DISPATCH\") called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 457\n\tCatalyst::forward(MediaWords=HASH(0xc4fe220), \"/api/v2/media/_DISPATCH\") called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Dispatcher.pm line 108\n\tCatalyst::Dispatcher::dispatch(Catalyst::Dispatcher=HASH(0x4fc8950), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 1973\n\tCatalyst::dispatch(MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Plugin/Static/Simple.pm line 86\n\tClass::MOP::Class:::around(CODE(0x4b35b40), MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 164\n\tMediaWords::_wrapped_dispatch(MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 95\n\tMediaWords::dispatch(MediaWords=HASH(0xc4fe220)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2364\n\tCatalyst::try {...} () called at /home/mediacloud/mediacloud/local/lib/perl5/Try/Tiny.pm line 81\n\teval {...} called at /home/mediacloud/mediacloud/local/lib/perl5/Try/Tiny.pm line 72\n\tTry::Tiny::try(CODE(0xeb77ec0), Try::Tiny::Catch=REF(0xc058a98)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst.pm line 2373\n\tCatalyst::handle_request(\"MediaWords\", \"env\", HASH(0xc0586a8), \"response_cb\", CODE(0xef34798)) called at /home/mediacloud/mediacloud/local/lib/perl5/Catalyst/Engine.pm line 796\n\tCatalyst::Engine::__ANON__(CODE(0xef34798)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Middleware/HTTPExceptions.pm line 32\n\tPlack::Middleware::HTTPExceptions::try {...} () called at /home/mediacloud/mediacloud/local/lib/perl5/Try/Tiny.pm line 81\n\teval {...} called at /home/mediacloud/mediacloud/local/lib/perl5/Try/Tiny.pm line 72\n\tTry::Tiny::try(CODE(0xc93e048), Try::Tiny::Catch=REF(0xc01ed58)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Middleware/HTTPExceptions.pm line 41\n\tPlack::Middleware::HTTPExceptions::__ANON__(CODE(0xc8ff318)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Util.pm line 301\n\tPlack::Util::__ANON__(CODE(0xc0e76c8)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Util.pm line 301\n\tPlack::Util::__ANON__(CODE(0xc0e9880)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Util.pm line 301\n\tPlack::Util::__ANON__(CODE(0xc0d9140)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Util.pm line 301\n\tPlack::Util::__ANON__(CODE(0xc01e950)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Util.pm line 301\n\tPlack::Util::__ANON__(CODE(0xc01ea70)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Handler/FCGI.pm line 136\n\tPlack::Handler::FCGI::run(Plack::Handler::FCGI=HASH(0xbf37be8), CODE(0xbf367f0)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Loader.pm line 84\n\tPlack::Loader::run(Plack::Loader=HASH(0x1beed28), Plack::Handler::FCGI=HASH(0xbf37be8)) called at /home/mediacloud/mediacloud/local/lib/perl5/Plack/Runner.pm line 277\n\tPlack::Runner::run(Plack::Runner=HASH(0x19e8aa8)) called at /home/mediacloud/mediacloud/local/bin/plackup line 7\""}"
status
:
500`

**Comment by cindyloo** [comment]
some refactoring blitzed the returned media_id so will update` collectionedit.py`
