### ISSUE TITLE
fix date editing during topic creation wizard

### ISSUE THREAD

**Issue by hroberts** [mitmedialab/MediaCloud-Web-Tools#526]
Editing dates during the topic creation process after previewing at least once is broken:

* go to create topic page
* enter end date of current day and start date in the future
* click on preview
* click on previous
* fix start date to be in the past

After these steps, creating a topic will still fail with an api error complaining about the future start date.

**Comment by hroberts** [comment]
seems like a broader session problem.  when I click back button enough times to get all the way back to the topic mapper home page, then choose 'create topic' from the menu, all of the form fields remain filled out and the date editing bug abides.

**Comment by cindyloo** [comment]
related to #530 - could not reproduce after that fix...successfully created topic after following use case
