### ISSUE TITLE
save search button on explorer does nothing

### ISSUE THREAD

**Issue by hroberts** [mitmedialab/MediaCloud-Web-Tools#905]
When I click on 'save search' in the explorer in firefox with the following url, nothing happens:

https://explorer.mediacloud.org/#/queries/search?q=[{%22label%22:%22trump%22,%22q%22:%22trump%22,%22color%22:%22%231f77b4%22,%22startDate%22:%222016-11-08%22,%22endDate%22:%222017-09-01%22,%22sources%22:[],%22collections%22:[9360524]},{%22label%22:%22trump%20or%20clinton%22,%22q%22:%22trump%20or%20clinton%22,%22color%22:%22#ff7f0e%22,%22startDate%22:%222016-11-08%22,%22endDate%22:%222017-09-01%22,%22sources%22:[],%22collections%22:[9360524]},{%22label%22:%22trump%20or%20clinton%20or%20obama%20or%20repub*%20or%20democrat*%22,%22q%22:%22trump%20or%20clinton%20or%20obama%20or%20repub*%20or%20democrat*%22,%22color%22:%22#2ca02c%22,%22startDate%22:%222016-11-08%22,%22endDate%22:%222017-09-01%22,%22sources%22:[],%22collections%22:[9360524]}]

This happens whether I load the page from scratch using the url (which generated the quoting error) or when I had just developed the url in the page without yet reloading (but I had done so over the course a ~12 hour browser session).

**Comment by hroberts** [comment]
when I start a new session  with a simple search, the save search button works fine.

**Comment by cindyloo** [comment]
hm.. looks like something broke. will check into

**Comment by cindyloo** [comment]
I think the fixes I made to the encoding of the url ( the color, etc) also fixed this bug - because now I can't replicate.
