### ISSUE TITLE
second of three queries does not get auto-named

### ISSUE THREAD

**Issue by hroberts** [mitmedialab/MediaCloud-Web-Tools#916]
1. go to explorer.mediacloud.org
2. type 'foo' into search box and hit enter
3. click add query
4. type 'bar' into query box
5. click add query
6. type 'baz' into query box
7. click 'search'

I end up with three queries: foo, Query B, and baz.

**Comment by cindyloo** [comment]
ah ok.. triggering the auto-naming is still a little buggy going from one widget to the next, depending on how you interact with the adds and the Search button - we have a few different events we are trapping. will look into

**Comment by cindyloo** [comment]
set up autoNaming in `UrlBasedQueryContainer's componentWillMount`. Test whether the URL came from the homepage or just a URL load. If the former, allow automagic. If the latter, do not (on the queries read in).
